config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to '/books'
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div class="errors-box">
    <div class="errors-title"><strong><%= @book.errors.count %> errors prohibited this book from being saved:</strong></div>
    <ul class="errors-message" type="square">
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1>Editing Book</h1>
<%= form_with model: @book do |f| %>

  <div class="form-box">
    <p class="form-text">Title</p>
    <%= f.text_field :title %>
  </div>
  <div class="form-box">
    <p class="form-text">Body</p>
    <%= f.text_area :body %>
  </div>
    <%= f.submit 'Update Book' %>

<% end %>

<div class="link-content">
  <span class="edit-link1">
    <%= link_to "Show", book_path(@book.id) %>
  </span>
  <span class="edit-link2">
    <%= link_to "Back", books_path %>
  </span>
</div>

app/views/books/index.html.erb
  <h1>Books</h1>
  <table class="index-list">
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
　　　  　<td><%= link_to "Show", book_path(book.id) %></td>
　　　　  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
　　　　  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <h2>New book</h2>
  <% if @book.errors.any? %>
    <div class="errors-box">
      <div class="errors-title"><strong><%= @book.errors.count %> errors prohibited this book from being saved:</strong></div>
      <ul class="errors-message" type="square">
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @book do |f| %>
    <div class="form-box">
      <p class="form-text">Title</p>
      <%= f.text_field :title %>
    </div>
    <div class="form-box">
      <p class="form-text">Body</p>
      <%= f.text_area :body %>
    </div>
      <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<div class="view-box">
  <h4 class="view-text">Title:</h4>
  <span class="view-textbox"><%= @book.title %></span>
</div>
<div class="view-box">
  <h4 class="view-text">Body:</h4>
  <span class="view-textbox"><%= @book.body %></span>
</div>

<div class="link-content">
  <span class="show-link1">
    <%= link_to "Edit", edit_book_path(@book.id) %>
  </span>
  <span class="show-link2">
    <%= link_to "Back", books_path %>
  </span>
</div>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<p class="top">
<strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます<br>
<%= link_to "start", books_path  %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <div class="flash-message">
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>